-- MySQL Script generated by MySQL Workbench
-- śro, 18 mar 2020, 17:39:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE DATABASE biblioteka;
-- -----------------------------------------------------
-- Schema biblioteka
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteka
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteka` DEFAULT CHARACTER SET latin1 ;
USE `biblioteka` ;

-- -----------------------------------------------------
-- Table `biblioteka`.`czytelnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteka`.`czytelnik` (
  `id_czytelnik` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Klucz główny przydzielony automatycznie',
  `login` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL COMMENT 'Nazwa czytelnika potrzeba przy logowaniu.',
  `haslo` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL COMMENT 'Hasło niezaszyfrowane',
  `imie` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL COMMENT 'Imię ',
  `nazwisko` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL COMMENT 'Nazwisko',
  `adres` VARCHAR(200) CHARACTER SET 'utf8' NOT NULL COMMENT 'Adres zamieszkania np.: ul. Przykład 3/12',
  `miasto` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL COMMENT 'Miasto',
  `wojewodztwo` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL COMMENT 'Nazwa województwa',
  `telefon` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT 'Telefony',
  `kod_pocztowy` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL COMMENT 'Kod pocztowy',
  `email` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL COMMENT 'Adres e-mail',
  PRIMARY KEY (`id_czytelnik`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1
COMMENT = 'Posiada informacje o czytelnikach zarejestrowanych w programie.';


-- -----------------------------------------------------
-- Table `biblioteka`.`kategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteka`.`kategoria` (
  `id_kategoria` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Klucz główny przydzielony automatycznie',
  `nazwa` VARCHAR(200) CHARACTER SET 'utf8' NOT NULL COMMENT 'Nazwa kategorii',
  PRIMARY KEY (`id_kategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabela zawierająca wszystkie kategorie książek w systemie.';


-- -----------------------------------------------------
-- Table `biblioteka`.`ksiazka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteka`.`ksiazka` (
  `id_ksiazka` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Klucz główny przydzielony automatycznie',
  `id_kategoria` INT(11) NOT NULL COMMENT 'Klucz obcy z tabeli kategoria',
  `isbn` VARCHAR(13) CHARACTER SET 'utf8' NOT NULL COMMENT 'Niepowtarzalny 13-cyfrowy identyfikator książki',
  `tytul` VARCHAR(200) CHARACTER SET 'utf8' NOT NULL COMMENT 'Tytuł książki',
  `autor` VARCHAR(70) CHARACTER SET 'utf8' NOT NULL COMMENT 'Imię i Nazwisko autora książki',
  `stron` INT(4) NOT NULL COMMENT 'Liczba stron książki',
  `wydawnictwo` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL COMMENT 'Nazwa wydawnictwa, w którym wydano książkę',
  `rok_wydania` INT(4) NOT NULL COMMENT 'Rok wydania książki',
  `opis` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT 'Opis książki',
  PRIMARY KEY (`id_ksiazka`),
  INDEX `fk_ksiazka_kategoria1_idx` (`id_kategoria` ASC) VISIBLE,
  CONSTRAINT `fk_ksiazka_kategoria1`
    FOREIGN KEY (`id_kategoria`)
    REFERENCES `biblioteka`.`kategoria` (`id_kategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = latin1
COMMENT = 'Wszystkie książki dodane do bazy danych.';


-- -----------------------------------------------------
-- Table `biblioteka`.`magazyn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteka`.`magazyn` (
  `id_magazyn` INT(11) NOT NULL AUTO_INCREMENT,
  `ksiazka_id` INT(11) NOT NULL,
  `ilosc` INT(11) NULL DEFAULT '10',
  PRIMARY KEY (`id_magazyn`),
  INDEX `fk_magazyn_ksiazka1_idx` (`ksiazka_id` ASC) VISIBLE,
  CONSTRAINT `fk_magazyn_ksiazka1`
    FOREIGN KEY (`ksiazka_id`)
    REFERENCES `biblioteka`.`ksiazka` (`id_ksiazka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `biblioteka`.`zamowienie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteka`.`zamowienie` (
  `id_zamowienie` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Klucz główny przydzielony automatycznie',
  `id_czytelnik` INT(11) NOT NULL COMMENT 'Klucz obcy z tabeli czytelnik',
  `data_zamowienia` DATETIME NOT NULL COMMENT 'Data złożenia zamówienia w bibliotece',
  `data_zwrotu` DATETIME NULL DEFAULT NULL COMMENT 'Data zwrotu książki do biblioteki',
  PRIMARY KEY (`id_zamowienie`),
  INDEX `fk_zamowienie_czytelnik1_idx` (`id_czytelnik` ASC) VISIBLE,
  CONSTRAINT `fk_zamowienie_czytelnik1`
    FOREIGN KEY (`id_czytelnik`)
    REFERENCES `biblioteka`.`czytelnik` (`id_czytelnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1
COMMENT = 'Posiada informacje o zamówionych, wypożyczonych czy oddanych książkach w bibliotece.';


-- -----------------------------------------------------
-- Table `biblioteka`.`zamowienieKsiazka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteka`.`zamowienieKsiazka` (
  `zamowienieKsiazka_id` INT(11) NOT NULL AUTO_INCREMENT,
  `ksiazka_id` INT(11) NOT NULL,
  `zamowienie_id` INT(11) NOT NULL,
  PRIMARY KEY (`zamowienieKsiazka_id`),
  INDEX `fk_zamowienieKsiazka_ksiazka1_idx` (`ksiazka_id` ASC) VISIBLE,
  INDEX `fk_zamowienieKsiazka_zamowienie1_idx` (`zamowienie_id` ASC) VISIBLE,
  CONSTRAINT `fk_zamowienieKsiazka_ksiazka1`
    FOREIGN KEY (`ksiazka_id`)
    REFERENCES `biblioteka`.`ksiazka` (`id_ksiazka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zamowienieKsiazka_zamowienie1`
    FOREIGN KEY (`zamowienie_id`)
    REFERENCES `biblioteka`.`zamowienie` (`id_zamowienie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;

INSERT INTO biblioteka.kategoria VALUES(1, 'Biznes');
INSERT INTO biblioteka.kategoria VALUES(2, 'Poradniki');
INSERT INTO biblioteka.kategoria VALUES(3, 'Programowanie');
INSERT INTO biblioteka.kategoria VALUES(4, 'Programowanie mobilne');
INSERT INTO biblioteka.kategoria VALUES(5, 'Webmasterstwo');
INSERT INTO biblioteka.kategoria vALUES(6, 'Systemy operacyjne');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
