# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 546)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonAfterTime = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonAfterTime.setObjectName("pushButtonAfterTime")
        self.horizontalLayout.addWidget(self.pushButtonAfterTime)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableViewOrders = QtWidgets.QTableView(self.centralWidget)
        self.tableViewOrders.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableViewOrders.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableViewOrders.setObjectName("tableViewOrders")
        self.tableViewOrders.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_3.addWidget(self.tableViewOrders)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.tableViewDetails = QtWidgets.QTableView(self.centralWidget)
        self.tableViewDetails.setObjectName("tableViewDetails")
        self.tableViewDetails.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tableViewDetails)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuWidok = QtWidgets.QMenu(self.menuBar)
        self.menuWidok.setObjectName("menuWidok")
        self.menuPlik = QtWidgets.QMenu(self.menuBar)
        self.menuPlik.setObjectName("menuPlik")
        self.menuUstawienia = QtWidgets.QMenu(self.menuBar)
        self.menuUstawienia.setObjectName("menuUstawienia")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionZamknij = QtWidgets.QAction(MainWindow)
        self.actionZamknij.setObjectName("actionZamknij")
        self.actionKsiazka = QtWidgets.QAction(MainWindow)
        self.actionKsiazka.setObjectName("actionKsiazka")
        self.actionCzytelnik = QtWidgets.QAction(MainWindow)
        self.actionCzytelnik.setObjectName("actionCzytelnik")
        self.actionMagazyn = QtWidgets.QAction(MainWindow)
        self.actionMagazyn.setObjectName("actionMagazyn")
        self.actionNoweZamowienie = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("nowe.png")
        self.actionNoweZamowienie.setIcon(icon)
        self.actionNoweZamowienie.setObjectName("actionNoweZamowienie")
        self.actionPolaczenie = QtWidgets.QAction(MainWindow)
        self.actionPolaczenie.setObjectName("actionPolaczenie")
        self.menuWidok.addAction(self.actionKsiazka)
        self.menuWidok.addAction(self.actionCzytelnik)
        self.menuWidok.addAction(self.actionMagazyn)
        self.menuPlik.addAction(self.actionNoweZamowienie)
        self.menuPlik.addAction(self.actionZamknij)
        self.menuUstawienia.addAction(self.actionPolaczenie)
        self.menuBar.addAction(self.menuPlik.menuAction())
        self.menuBar.addAction(self.menuWidok.menuAction())
        self.menuBar.addAction(self.menuUstawienia.menuAction())
        self.toolBar.addAction(self.actionNoweZamowienie)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Zamowienia:"))
        self.pushButtonAfterTime.setText(_translate("MainWindow", "Po terminie"))
        self.label_2.setText(_translate("MainWindow", "Pozycje:"))
        self.menuWidok.setTitle(_translate("MainWindow", "Widok"))
        self.menuPlik.setTitle(_translate("MainWindow", "Plik"))
        self.menuUstawienia.setTitle(_translate("MainWindow", "Ustawienia"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionZamknij.setText(_translate("MainWindow", "Zamknij"))
        self.actionKsiazka.setText(_translate("MainWindow", "Książka"))
        self.actionCzytelnik.setText(_translate("MainWindow", "Czytelnik"))
        self.actionMagazyn.setText(_translate("MainWindow", "Magazyn"))
        self.actionNoweZamowienie.setText(_translate("MainWindow", "Nowe zamówienie"))
        self.actionNoweZamowienie.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionPolaczenie.setText(_translate("MainWindow", "Połączenie"))
